from __future__ import annotations

# Trend-following strategy parameters (code defaults).

MAX_SL_DISTANCE: float = 0.02

# Breakout retest entry filters
TREND_BREAKOUT_RETEST_BLOCK_SYMBOLS: tuple[str, ...] = ("FETUSDT", "RENDERUSDT")
TREND_BREAKOUT_RETEST_MAX_LEVEL_DEV: float = 0.0080
TREND_BREAKOUT_RETEST_MIN_BODY_RATIO: float = 0.10
TREND_BREAKOUT_RETEST_MIN_RECLAIM_PCT: float = 0.0000
TREND_BREAKOUT_RETEST_MIN_VOL_RATIO: float = 0.50
TREND_BREAKOUT_RETEST_LONG_RSI_MIN: float = 45.0
TREND_BREAKOUT_RETEST_SHORT_RSI_MAX: float = 55.0

# Pullback entry filters
PULLBACK_EMA_SLOPE_MIN: float = 0.0005
PULLBACK_LONG_RSI_MIN: float = 51.0
PULLBACK_SHORT_RSI_MAX: float = 49.0
TREND_PULLBACK_MAX_EMA_DEV: float = 0.0120
TREND_PULLBACK_IMPULSE_PCT_MIN: float = 0.015
TREND_PULLBACK_SELECT_MARGIN: float = 2.5
TREND_PULLBACK_SCORE_BONUS: float = 1.25
TREND_PULLBACK_RECLAIM_BODY_RATIO: float = 0.25
TREND_PULLBACK_VOL_CONFIRM_RATIO: float = 1.0

# Stop/TP construction
STOP_ATR_MULT: float = 0.8
TREND_BREAKOUT_STOP_ATR_MULT: float = 0.8
TREND_STOP_ATR_MULT: float = 0.5
TREND_TP_STRUCTURE_LOOKBACK_15M: int = 96
TREND_TP_STRUCTURE_MIN_SEPARATION_PCT: int = 15

TREND_EXTENDED_EMA_FRAC: float = 0.007
TREND_EXHAUSTION_EMA_WEIGHT: float = 0.34
TREND_EXHAUSTION_ATR_SPIKE_WEIGHT: float = 0.28
TREND_EXHAUSTION_IMPULSE_WEIGHT: float = 0.22
TREND_EXHAUSTION_WICK_WEIGHT: float = 0.16
TREND_BREAKOUT_EXHAUSTION_WEIGHT: float = 0.46
TREND_BREAKOUT_COMPRESSION_BOOST: float = 0.16
TREND_BREAKOUT_NO_COMPRESSION_MULT: float = 0.83
TREND_PULLBACK_EXTENDED_BOOST: float = 1.05
TREND_COMPRESSION_GATE_MIN: float = 0.36
TREND_BREAKOUT_PARABOLIC_EXHAUSTION: float = 0.92
TREND_BREAKOUT_MAX_BAD_WICK_MULT: float = 0.72
TREND_BREAKOUT_WEAK_CLOSE_MULT: float = 0.78
TREND_BREAKOUT_EMA_OVEREXTENSION_WEIGHT: float = 0.38

# Pullback continuation quality
TREND_PULLBACK_MISALIGN_MULT: float = 0.58
TREND_PULLBACK_MISALIGN_MIN_RECLAIM: float = 0.62
TREND_PULLBACK_MISALIGN_MIN_COMPRESSION: float = 0.42
TREND_PULLBACK_IMPULSE_MIN_COMPRESSION: float = 0.18
TREND_PULLBACK_LOW_CONVICTION_ADX_BELOW: float = 22.0
TREND_PULLBACK_LOW_CONVICTION_COMP_BELOW: float = 0.75
TREND_PULLBACK_LOW_CONVICTION_MULT: float = 0.42


# Breakout near-miss grade admission
TREND_BREAKOUT_NEAR_MISS_MIN_SCORE: int = 8
TREND_BREAKOUT_NEAR_MISS_MIN_CONFIDENCE: float = 0.45

# Soft ADX penalties on setup raw score (15m/1H ADX; breakout & pullback).
TREND_FOLLOWING_ADX_PERIOD: int = 14
TREND_FOLLOWING_ADX_SOFT_TIER1_BELOW: float = 18.0
TREND_FOLLOWING_ADX_SOFT_TIER1_MULT: float = 0.85
TREND_FOLLOWING_ADX_SOFT_TIER2_BELOW: float = 15.0
TREND_FOLLOWING_ADX_SOFT_TIER2_MULT: float = 0.70
TREND_FOLLOWING_ANALYTICS_LOG: bool = False

# --- Production trend regime detector (1H gate for trend-following / selector) ---
TREND_REGIME_FILTER: bool = True
TREND_REGIME_ADX_MIN: float = 22.0  # legacy; not a hard reject floor in detector
TREND_REGIME_ADX_CATASTROPHIC: float = 10.0
TREND_REGIME_CHOP_EMA_FRAC: float = 0.004
TREND_REGIME_MIN_BARS_1H: int = 90
TREND_REGIME_ADX_PERIOD: int = 14
TREND_REGIME_ADX_NORM_LO: float = 15.0
TREND_REGIME_ADX_NORM_HI: float = 45.0
TREND_REGIME_EMA_FAST: int = 20
TREND_REGIME_EMA_SLOW: int = 50
TREND_REGIME_SLOPE_BARS: int = 5
TREND_REGIME_SLOPE_REF_FRAC: float = 0.003
TREND_REGIME_BREAKOUT_LOOKBACK: int = 24
TREND_REGIME_ATR_PERIOD: int = 14
TREND_REGIME_VOL_RATIO_LO: float = 0.92
TREND_REGIME_VOL_RATIO_HI: float = 1.35
TREND_REGIME_W_ADX: float = 0.22
TREND_REGIME_W_SLOPE: float = 0.18
TREND_REGIME_W_BREAKOUT: float = 0.14
TREND_REGIME_W_HTF: float = 0.18
TREND_REGIME_W_VOL: float = 0.14
TREND_REGIME_W_PERSIST: float = 0.14
TREND_REGIME_MIN_STRENGTH: float = 0.22
TREND_REGIME_VOL_THIN_RATIO: float = 0.35
TREND_REGIME_THIN_VOL_PENALTY: float = 0.90

SELECTOR_TREND_GATE_SOFTNESS: float = 0.12
SELECTOR_REVERSAL_TREND_HEADWIND: float = 0.0
SELECTOR_TREND_MIN_STRENGTH_TO_COMPETE: float = 0.35
SELECTOR_TREND_MIN_STRENGTH_EPS: float = 0.001
SELECTOR_DYNAMIC_MIN_SCORE_STRONG_TREND: float = 0.70
TREND_REQUIRE_REGIME_DIRECTION_MATCH: bool = True
